### ISSUE TITLE
Consent Options Hash Issue

### ISSUE THREAD

**Issue by cbratschi** [lukaskupczyk/react-hook-consent#20]
Our consent options depend on the language of the site and whenever a user switches to another language the cookie banner appears again.

Therefore the hash calculation should not relay on any user texts. Using the cookie names should be sufficient.

**Comment by cbratschi** [comment]
Best solution would be to add a versioning function which by default uses the hash but can be overwritten by using a different handling. I would like to use fixed version numbers in our config files.

**Comment by lukaskupczyk** [comment]
I have added a `customHash` property where you can define your individual hash. It is included in version 3.4.0. Please let me know what you think.

**Comment by cbratschi** [comment]
@lukaskupczyk Thanks a lot, works fine now.
