### ISSUE TITLE
feature request: consent for local storage

### ISSUE THREAD

**Issue by cachho** [lukaskupczyk/react-hook-consent#21]
You need consent for local storage, just like you do for cookies. In the readme I couldn't find that you could ask for permission for local storage.

I guess I could just add a cookie for each local storage key, but I think this would be a need feature.

What do you think?

**Comment by cachho** [comment]
@lukaskupczyk yes exactly.

I currently use CCM19 and it treats cookies just like it treats session storage and local storage. and from my (not a lawyer) perspective, I don't see why they shouldn't be.

**Comment by lukaskupczyk** [comment]
Thank you for your kind feedback. I will put this feature on my todo list.
